# Generated by Django 3.2.9 on 2021-11-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0000000', max_length=20)),
                ('age', models.CharField(default='0000000', max_length=20)),
                ('gender', models.CharField(default='0000000', max_length=20)),
                ('medicalpractitioner', models.CharField(default='0000000', max_length=20)),
                ('seniorcitizen', models.CharField(default='0000000', max_length=20)),
                ('trainno', models.CharField(default='0000000', max_length=20)),
                ('trainname', models.CharField(default='0000000', max_length=20)),
                ('classname', models.CharField(default='0000000', max_length=20)),
                ('noofseat', models.CharField(default='0000000', max_length=20)),
                ('stationfrom', models.CharField(default='0000000', max_length=20)),
                ('stationto', models.CharField(default='0000000', max_length=20)),
            ],
        ),
    ]
